backend:
  name: git-gateway
  branch: 48891 # La tua branch principale, solitamente 'main' o 'master'

media_folder: "assets/uploads" # Dove saranno caricate le immagini
public_folder: "/assets/uploads" # Path pubblico per le immagini

collections:
  - name: "vp"
    label: "VP Pages"
    folder: "links"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "cartella" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Link"
        name: "links"
        widget: "list"
        fields:
          - { label: "Nome", name: "name", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
  
  - name: "page" # Nome della collection, che corrisponde ai post
    label: "Post"
    folder: "it" # La cartella dove sono i post in Jekyll
    create: true # Permette di creare nuovi post
    slug: "{{title}}" # Struttura del nome dei file
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime", default: "now" } # Data automatica
      - { label: "Contenuto", name: "body", widget: "markdown" }

  - name: "book" # Nome della collection, che corrisponde ai post
    label: "Book"
    folder: "_libri" # La cartella dove sono i post in Jekyll
    create: true # Permette di creare nuovi post
    slug: "{{title}}" # Struttura del nome dei file
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Esempio intro", name: "intro", widget: "string" }
      - { label: "Autore", name: "author", widget: "string" }
      - { label: "Anno", name: "year", widget: "string" }
      - { label: "Genere", name: "genere", widget: "string" }
      - { label: "Numero", name: "n", widget: "string" }
      - { label: "Stato", name: "stato", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "book" }
